[package]
name = "twoskip"
version = "0.1.0"
edition = "2021"
authors = ["Rob N ★ <robn@despairlabs.com>"]
license = "MIT"
repository = "https://github.com/robn/twoskip-rs"

[dependencies]
memmap2 = "0.9.0"
byteorder = "1.5.0"
crc = "3.0.1"
num = "0.4.1"
